In [82]:
# Import dependencies
import pandas as pd
import numpy as np
import datetime as dt

In [83]:
# Declare modified dfs 
modified_deal_df = pd.read_csv('../Modified_Data_Resources/modified_deal_info.csv')
modified_mockups_df = pd.read_csv('../Modified_Data_Resources/modified_mockups_info.csv')
modified_revisions_df = pd.read_csv('../Modified_Data_Resources/revisions_df_copy.csv')
modified_cart_items_df = pd.read_csv('../Modified_Data_Resources/modified_cart_items_info.csv')
modified_mfg_products_df = pd.read_csv('../Modified_Data_Resources/mfg_products_df_copy.csv')
modified_deals_mockups_df = pd.read_csv('../Modified_Data_Resources/deals_mockups_df_copy.csv')

C:\Users\KatreeceHattaway\AppData\Local\Temp\ipykernel_8352\3617479974.py:2: DtypeWarning: Columns (25,33,34,48) have mixed types. Specify dtype option on import or set low_memory=False.
  modified_deal_df = pd.read_csv('../Modified_Data_Resources/modified_deal_info.csv')
C:\Users\KatreeceHattaway\AppData\Local\Temp\ipykernel_8352\3617479974.py:3: DtypeWarning: Columns (51,53) have mixed types. Specify dtype option on import or set low_memory=False.
  modified_mockups_df = pd.read_csv('../Modified_Data_Resources/modified_mockups_info.csv')
C:\Users\KatreeceHattaway\AppData\Local\Temp\ipykernel_8352\3617479974.py:5: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  modified_cart_items_df = pd.read_csv('../Modified_Data_Resources/modified_cart_items_info.csv')

# Transform Data for Design

- Drop unnecessary columns, rename and updated values to create a schema specific for design team queries

In [84]:
# Clean up modified Deal_df
# Only keep key columns for design schema

# Dictionary for renaming columns
rename_columns = {
    'ID': 'Deal_Table_Record_ID',
    'Created at': 'Deal_Created_at',
    'Updated at': 'Deal_Updated_at',
    'Originial due at': 'Deal_Original_Due_at',
    'Due at': 'Deal_Due_at',
    'Assigned at': 'Deal_assigned_at',
    'Mockups ready at': 'Mockups_ready_at',  
    'Mockup due date': 'Mockup_due_date',  
    'Hs quantity': 'Hs_quantity',  
    'Hs client type': 'Hs_client_type',  
    'Po number': 'Po_number',  
    'Portal created': 'Portal_created',  
    'Hs design difficulty': 'Hs_design_difficulty',  
    'Automation tool': 'Automation_tool',  
    'Hs dealtype': 'Hs_dealtype',  
    'Created on': 'Deal_Created_on'  
}

# Filter and rename columns in the DataFrame
cleaned_design_deal_df = modified_deal_df[list(rename_columns.keys())].rename(columns=rename_columns)

# Display the new DataFrame
cleaned_design_deal_df.head()

,Deal_Table_Record_ID,Deal_Created_at,Deal_Updated_at,Deal_Original_Due_at,Deal_Due_at,Deal_assigned_at,Mockups_ready_at,Mockup_due_date,Hs_quantity,Hs_client_type,Po_number,Portal_created,Hs_design_difficulty,Automation_tool,Hs_dealtype,Deal_Created_on
0,105010,2023-01-01T19:01:33.103Z,2024-02-09T00:35:28.466Z,2023-01-04T19:01:33.000Z,2023-01-04T19:01:33.000Z,2023-01-03T15:28:27.124Z,2023-01-03T17:14:33.056Z,2023-01-04T06:00:00.000Z,NaN,Direct,NaN,True,Low,1.0,Newbusiness,2023-01-01
1,105014,2023-01-01T23:52:14.779Z,2023-03-02T22:51:26.182Z,2023-01-04T23:52:16.000Z,2023-01-04T23:52:16.000Z,2023-01-03T15:28:57.563Z,2023-01-03T15:34:23.973Z,2023-01-04T06:00:00.000Z,NaN,Direct,NaN,True,High Res Preview,2.0,Newbusiness,2023-01-01
2,105006,2023-01-01T04:58:07.689Z,2023-01-11T15:50:19.497Z,NaN,NaN,NaN,NaN,NaN,NaN,Direct,NaN,True,NaN,1.0,Newbusiness,2023-01-01
3,105011,2023-01-01T20:05:07.001Z,2023-03-28T15:29:19.886Z,2023-01-04T20:05:09.000Z,2023-01-04T20:05:09.000Z,2023-01-03T15:30:15.651Z,2023-01-03T22:16:32.764Z,2023-01-04T06:00:00.000Z,NaN,Direct,NaN,True,Low,2.0,Newbusiness,2023-01-01
4,105007,2023-01-01T14:26:53.422Z,2023-01-16T19:29:55.241Z,2023-01-04T14:26:55.000Z,2023-01-04T14:26:55.000Z,2023-01-03T15:29:39.647Z,NaN,2023-01-04T06:00:00.000Z,NaN,Direct,NaN,True,High Res Preview,2.0,Newbusiness,2023-01-01

In [85]:
# Update Cleaned Deal df Dtypes accordingly

# Columns to convert to datetime
datetime_columns = [
    'Deal_Created_at', 'Deal_Updated_at', 'Deal_Original_Due_at',
    'Deal_Due_at', 'Deal_assigned_at', 'Mockups_ready_at', 
    'Mockup_due_date', 'Deal_Created_on'
]

for col in datetime_columns:
    cleaned_design_deal_df[col] = pd.to_datetime(cleaned_design_deal_df[col], errors='coerce')

# Columns to convert to integer
int_columns = {
    'Hs_quantity': 'Int64', 
    'Po_number': 'Int64',
    'Automation_tool': 'Int64'
}

for col, dtype in int_columns.items():
    cleaned_design_deal_df[col] = cleaned_design_deal_df[col].astype(dtype)

# Check the DataFrame's new dtypes
print(cleaned_design_deal_df.dtypes)

Deal_Table_Record_ID                  int64
Deal_Created_at         datetime64[ns, UTC]
Deal_Updated_at         datetime64[ns, UTC]
Deal_Original_Due_at    datetime64[ns, UTC]
Deal_Due_at             datetime64[ns, UTC]
Deal_assigned_at        datetime64[ns, UTC]
Mockups_ready_at        datetime64[ns, UTC]
Mockup_due_date         datetime64[ns, UTC]
Hs_quantity                           Int64
Hs_client_type                       object
Po_number                             Int64
Portal_created                       object
Hs_design_difficulty                 object
Automation_tool                       Int64
Hs_dealtype                          object
Deal_Created_on              datetime64[ns]
dtype: object

In [86]:
# Clean up modified Mockup df 
# Only keep key columns for design schema

# Dictionary for renaming columns
rename_columns = {
    'ID': 'Mockup_ID',
    'Created at': 'mockup_created_at',
    'Updated at': 'Mockup_updated_at',
    'Version number': 'Version_number',  
    'Design number': 'Design_number', 
    'Chassis': 'Chassis',
    'Previously ordered': 'Previously_ordered',  
    'Design source': 'Design_source',  
    'Designer ID': 'Designer_ID',  
    'Parent mockup ID': 'Parent_mockup_ID'  
}

# Filter and rename columns in the DataFrame
cleaned_design_mockup_df = modified_mockups_df[list(rename_columns.keys())].rename(columns=rename_columns)

# Display the new DataFrame
cleaned_design_mockup_df

,Mockup_ID,mockup_created_at,Mockup_updated_at,Version_number,Design_number,Chassis,Previously_ordered,Design_source,Designer_ID,Parent_mockup_ID
0,134251,2023-01-01T17:18:48.886Z,2023-01-01T17:19:24.088Z,1.0,2,10,NaN,NaN,51627.0,NaN
1,134250,2023-01-01T17:17:48.918Z,2023-01-01T17:18:24.778Z,1.0,1,10,NaN,NaN,51627.0,NaN
2,134249,2023-01-01T14:26:54.516Z,2023-01-01T14:27:30.816Z,1.0,1,10,NaN,NaN,51627.0,NaN
3,134248,2023-01-01T05:02:06.108Z,2023-01-01T05:02:43.327Z,1.0,1,10,NaN,NaN,NaN,NaN
4,134253,2023-01-01T23:52:15.910Z,2023-01-03T15:34:00.373Z,1.0,1,10,NaN,NaN,47612.0,NaN
...,...,...,...,...,...,...,...,...,...,...
88302,235276,2024-04-09T16:38:43.716Z,2024-04-09T16:39:54.581Z,1.0,3,10,NaN,manual,467.0,NaN
88303,235248,2024-04-09T15:05:49.209Z,2024-04-09T15:06:39.937Z,1.0,3,10,NaN,manual,464.0,NaN
88304,235239,2024-04-09T11:18:29.065Z,2024-04-09T14:05:40.747Z,1.0,4,10,NaN,hrp,59292.0,NaN
88305,235259,2024-04-09T15:19:43.515Z,2024-04-09T15:22:32.166Z,1.0,5,10,NaN,hrp,61286.0,NaN
88306,235246,2024-04-09T14:25:08.962Z,2024-04-09T14:25:11.103Z,1.0,5,10,NaN,hrp,61070.0,NaN

In [87]:
# Update Cleaned Mockup df Dtypes accordingly

# Convert columns to datetime
datetime_columns = ['mockup_created_at', 'Mockup_updated_at', 'Previously_ordered']
for col in datetime_columns:
    cleaned_design_mockup_df[col] = pd.to_datetime(cleaned_design_mockup_df[col], errors='coerce')

# Convert columns to integer (where applicable)
int_columns = {
    'Version_number': 'Int64',  # Nullable integer type due to NaNs
    'Design_number': 'int',     # Non-nullable integer type
    'Chassis': 'int',           # Non-nullable integer type
    'Designer_ID': 'Int64',     # Nullable integer type due to NaNs
    'Parent_mockup_ID': 'Int64' # Highly nullable, using nullable integer type
}

for col, dtype in int_columns.items():
    cleaned_design_mockup_df[col] = cleaned_design_mockup_df[col].astype(dtype)

# Check the DataFrame's new dtypes
print(cleaned_design_mockup_df.dtypes)

Mockup_ID                           int64
mockup_created_at     datetime64[ns, UTC]
Mockup_updated_at     datetime64[ns, UTC]
Version_number                      Int64
Design_number                       int32
Chassis                             int32
Previously_ordered    datetime64[ns, UTC]
Design_source                      object
Designer_ID                         Int64
Parent_mockup_ID                    Int64
dtype: object

In [88]:
# Clean up modified Deals Mockups df
# Only keep key columns for design schema

# Dictionary for renaming columns
rename_columns = {
    'ID': 'Deals_mockups_ID',
    'Created at': 'Deals_Mockups_created_at',
    'Updated at': 'Deals_Mockups_updated_at'
}

# Columns to keep (including those to be renamed and those not renamed but still retained)
columns_to_keep = ['ID', 'Deal ID', 'Mockup ID', 'Created at', 'Updated at']

# Filter and rename columns in the DataFrame
cleaned_design_deals_mockups_df = modified_deals_mockups_df[columns_to_keep].rename(columns=rename_columns)

# Display the new DataFrame
cleaned_design_deals_mockups_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97586 entries, 0 to 97585
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Deals_mockups_ID          97586 non-null  int64
 1   Deal ID                   97586 non-null  int64
 2   Mockup ID                 97586 non-null  int64
 3   Deals_Mockups_created_at  97586 non-null  object
 4   Deals_Mockups_updated_at  97586 non-null  object
dtypes: int64(3), object(2)
memory usage: 3.7+ MB

In [89]:
# Update Cleaned Deals Mockups df Dtypes accordingly

# Convert columns to datetime
datetime_columns = ['Deals_Mockups_created_at', 'Deals_Mockups_updated_at']
for col in datetime_columns:
    cleaned_design_deals_mockups_df[col] = pd.to_datetime(cleaned_design_deals_mockups_df[col], errors='coerce')

# However, let's confirm the current data types to ensure everything is in order.
print(cleaned_design_deals_mockups_df.dtypes)

Deals_mockups_ID                          int64
Deal ID                                   int64
Mockup ID                                 int64
Deals_Mockups_created_at    datetime64[ns, UTC]
Deals_Mockups_updated_at    datetime64[ns, UTC]
dtype: object

In [90]:
# Clean up modified Cart Items df 
# Only keep key columns for design schema

# Dictionary for renaming columns
rename_columns = {
    'ID': 'cart_items_id',
    'Created at': 'Created_at',  # Assuming you want to keep the name almost similar but properly formatted
    'Quantity': 'Quantity',
    'Mockup ID': 'Mockup_ID',
    'Mockup version': 'Mockup_version',
    'Sock unit price': 'Sock_unit_price',
    'Pkg unit price': 'Pkg_unit_price',
    'Product ID': 'Product_ID',
    'Unit price': 'Unit_price',
    'Cart total': 'Cart_total',
    'Created on': 'Created_on'
}

# Columns to keep (specify columns here that you wish to keep in the new DataFrame)
columns_to_keep = list(rename_columns.keys())

# Filter and rename columns in the DataFrame
cleaned_design_cart_items_df = modified_cart_items_df[columns_to_keep].rename(columns=rename_columns)

# Display the new DataFrame
cleaned_design_cart_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33443 entries, 0 to 33442
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cart_items_id    33443 non-null  int64
 1   Created_at       33443 non-null  object
 2   Quantity         17297 non-null  float64
 3   Mockup_ID        16710 non-null  float64
 4   Mockup_version   16710 non-null  float64
 5   Sock_unit_price  17310 non-null  object
 6   Pkg_unit_price   11280 non-null  object
 7   Product_ID       461 non-null    float64
 8   Unit_price       461 non-null    object
 9   Cart_total       33442 non-null  float64
 10  Created_on       33443 non-null  object
dtypes: float64(5), int64(1), object(5)
memory usage: 2.8+ MB

In [91]:
# Update Cart Items df Dtypes accordingly

# Convert columns to datetime
datetime_columns = ['Created_at', 'Created_on']
for col in datetime_columns:
    cleaned_design_cart_items_df[col] = pd.to_datetime(cleaned_design_cart_items_df[col], errors='coerce')

# Convert columns to integer (handle NaNs appropriately if needed)
int_columns = {
    'Quantity': 'Int64',  # Nullable integer due to NaNs
    'Mockup_ID': 'Int64',  # Nullable integer due to NaNs
    'Mockup_version': 'Int64',  # Nullable integer due to NaNs
    'Product_ID': 'Int64',  # Nullable integer due to NaNs
    'Cart_total': 'Int64'  # Nullable integer due to NaNs
}

for col, dtype in int_columns.items():
    cleaned_design_cart_items_df[col] = cleaned_design_cart_items_df[col].astype(dtype)

# Handle money (currency) columns. Assuming you want to convert these from object to a numeric type like float.
money_columns = ['Sock_unit_price', 'Pkg_unit_price', 'Unit_price']
for col in money_columns:
    # Convert currency to float, assuming the currency is formatted as a string with a dollar sign, commas, etc.
    cleaned_design_cart_items_df[col] = cleaned_design_cart_items_df[col].replace(r'[\$,]', '', regex=True).astype(float)

# Check the DataFrame's new dtypes
print(cleaned_design_cart_items_df.dtypes)

cart_items_id                    int64
Created_at         datetime64[ns, UTC]
Quantity                         Int64
Mockup_ID                        Int64
Mockup_version                   Int64
Sock_unit_price                float64
Pkg_unit_price                 float64
Product_ID                       Int64
Unit_price                     float64
Cart_total                       Int64
Created_on              datetime64[ns]
dtype: object

In [92]:
# Clean up modified revision df 
# Keep key columns for design schema and rename

# Dictionary for renaming columns
rename_columns = {
    'ID': 'revisions_ID',
    'Mockup ID': 'Mockup_ID',  
    'Version number': 'Version_number',  
    'Completed at': 'Completed_at',  
    'Created at': 'Created_at',  
    'Updated at': 'Updated_at', 
    'Packaging ID': 'Packaging_ID',  
    'Product ID': 'Product_ID',  
    'Sock pair ID': 'Sock_pair_ID',  
    'Base version': 'Base_version',  
    'Read at': 'Read_at' 
}

# Columns to keep (specify columns here that you wish to keep in the new DataFrame)
columns_to_keep = list(rename_columns.keys())

# Filter and rename columns in the DataFrame
cleaned_design_revisions_df = modified_revisions_df[columns_to_keep].rename(columns=rename_columns)

# Display the new DataFrame
cleaned_design_revisions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20684 entries, 0 to 20683
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   revisions_ID    20684 non-null  int64
 1   Mockup_ID       16933 non-null  float64
 2   Version_number  16933 non-null  float64
 3   Completed_at    15925 non-null  object
 4   Created_at      20684 non-null  object
 5   Updated_at      20684 non-null  object
 6   Packaging_ID    2792 non-null   float64
 7   Product_ID      367 non-null    float64
 8   Sock_pair_ID    568 non-null    float64
 9   Base_version    16933 non-null  float64
 10  Read_at         7741 non-null   object
dtypes: float64(6), int64(1), object(4)
memory usage: 1.7+ MB

In [93]:
# Update cleaned Revisions df Dtypes

# Convert columns to datetime
datetime_columns = ['Completed_at', 'Created_at', 'Updated_at', 'Read_at']
for col in datetime_columns:
    cleaned_design_revisions_df[col] = pd.to_datetime(cleaned_design_revisions_df[col], errors='coerce')

# Convert columns to integer
int_columns = {
    'Mockup_ID': 'Int64',        # Nullable integer type due to NaNs
    'Version_number': 'Int64',   # Nullable integer type due to NaNs
    'Packaging_ID': 'Int64',     # Highly nullable, using nullable integer type
    'Product_ID': 'Int64',       # Highly nullable, using nullable integer type
    'Sock_pair_ID': 'Int64',     # Highly nullable, using nullable integer type
    'Base_version': 'Int64'      # Nullable integer type due to NaNs
}

for col, dtype in int_columns.items():
    cleaned_design_revisions_df[col] = cleaned_design_revisions_df[col].astype(dtype)

# Check the DataFrame's new dtypes to ensure changes were applied
print(cleaned_design_revisions_df.dtypes)

revisions_ID                    int64
Mockup_ID                       Int64
Version_number                  Int64
Completed_at      datetime64[ns, UTC]
Created_at        datetime64[ns, UTC]
Updated_at        datetime64[ns, UTC]
Packaging_ID                    Int64
Product_ID                      Int64
Sock_pair_ID                    Int64
Base_version                    Int64
Read_at           datetime64[ns, UTC]
dtype: object

In [94]:
# Clean up modified mfg products df
# Keep key columns for design schema and rename

# Dictionary for renaming columns
rename_columns = {
    'ID': 'mfg_products_ID',
    'Mockup ID': 'Mockup_ID',  
    'Created at': 'Created_at',  
    'Updated at': 'Updated_at',  
    'Packaging ID': 'Packaging_ID',  
    'Product ID': 'Product_ID',  
    'Sock pair ID': 'Sock_pair_ID',  
    'Created on': 'Created_on',  
    'Mockup version': 'Mockup_version', 
    'Quantity': 'Quantity',  
    'Product info ID': 'Product_info_ID' 
}

# Columns to keep (specify columns here that you wish to keep in the new DataFrame)
columns_to_keep = list(rename_columns.keys())

# Filter and rename columns in the DataFrame
cleaned_design_mfg_products_df = modified_mfg_products_df[columns_to_keep].rename(columns=rename_columns)

# Display the new DataFrame
cleaned_design_mfg_products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34383 entries, 0 to 34382
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   mfg_products_ID  34383 non-null  int64
 1   Mockup_ID        17136 non-null  float64
 2   Created_at       34383 non-null  object
 3   Updated_at       34383 non-null  object
 4   Packaging_ID     12281 non-null  float64
 5   Product_ID       496 non-null    float64
 6   Sock_pair_ID     1090 non-null   float64
 7   Created_on       34383 non-null  object
 8   Mockup_version   17136 non-null  float64
 9   Quantity         34382 non-null  float64
 10  Product_info_ID  29913 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 2.9+ MB

In [95]:
# Update Dtypes for cleaned MFG Products

# Convert columns to datetime
datetime_columns = ['Created_at', 'Updated_at', 'Created_on']
for col in datetime_columns:
    cleaned_design_mfg_products_df[col] = pd.to_datetime(cleaned_design_mfg_products_df[col], errors='coerce')

# Convert columns to integer (handle NaNs appropriately if needed)
int_columns = {
    'Mockup_ID': 'Int64',         # Nullable integer due to NaNs
    'Packaging_ID': 'Int64',      # Nullable integer due to NaNs
    'Product_ID': 'Int64',        # Highly nullable, using nullable integer type
    'Sock_pair_ID': 'Int64',      # Highly nullable, using nullable integer type
    'Mockup_version': 'Int64',    # Nullable integer due to NaNs
    'Quantity': 'Int64',          # Nullable integer due to NaNs
    'Product_info_ID': 'Int64'    # Nullable integer due to NaNs
}

for col, dtype in int_columns.items():
    cleaned_design_mfg_products_df[col] = cleaned_design_mfg_products_df[col].astype(dtype)

# Check the DataFrame's new dtypes to ensure changes were applied
print(cleaned_design_mfg_products_df.dtypes)

mfg_products_ID                  int64
Mockup_ID                        Int64
Created_at         datetime64[ns, UTC]
Updated_at         datetime64[ns, UTC]
Packaging_ID                     Int64
Product_ID                       Int64
Sock_pair_ID                     Int64
Created_on              datetime64[ns]
Mockup_version                   Int64
Quantity                         Int64
Product_info_ID                  Int64
dtype: object

# Write the cleaned CSVs to their own folder
 - Use the cleaned csvs for schema and import into Postgres

In [96]:
# write cleaned csvs to their own folder
cleaned_design_deal_df.to_csv('../Cleaned_Design_Data_Resources/cleaned_design_deal_df.csv', index=False)
cleaned_design_mockup_df.to_csv('../Cleaned_Design_Data_Resources/cleaned_design_mockup_df.csv', index=False)
cleaned_design_deals_mockups_df.to_csv('../Cleaned_Design_Data_Resources/cleaned_design_deals_mockups_df.csv', index=False)
cleaned_design_cart_items_df.to_csv('../Cleaned_Design_Data_Resources/cleaned_design_cart_items_df.csv', index=False)
cleaned_design_revisions_df.to_csv('../Cleaned_Design_Data_Resources/cleaned_design_revisions_df.csv', index=False)
cleaned_design_mfg_products_df.to_csv('../Cleaned_Design_Data_Resources/cleaned_design_mfg_products_df.csv', index=False)

In [105]:
#What was total incoming mockups AKA design requests in March 2023

# Assuming 'mockup_created_at' is a datetime column. If not, convert it:
cleaned_design_mockup_df['mockup_created_at'] = pd.to_datetime(cleaned_design_mockup_df['mockup_created_at'])

# Filter the DataFrame for entries in February 2023
february_mockups = cleaned_design_mockup_df[
    (cleaned_design_mockup_df['mockup_created_at'] >= '2023-02-01') &
    (cleaned_design_mockup_df['mockup_created_at'] <= '2023-02-28')
]

# Count unique Mockup_IDs
total_february_mockups = february_mockups['Mockup_ID'].nunique()
print("Total incoming mockups in February 2023:", total_february_mockups)

# Filter the DataFrame for entries in February 2024
february_2024_mockups = cleaned_design_mockup_df[
    (cleaned_design_mockup_df['mockup_created_at'] >= '2024-02-01') &
    (cleaned_design_mockup_df['mockup_created_at'] <= '2024-02-29')  # 2024 is a leap year
]

# Count unique Mockup_IDs
total_february_2024_mockups = february_2024_mockups['Mockup_ID'].nunique()
print("Total incoming mockups in February 2024:", total_february_2024_mockups)

Total incoming mockups in February 2023: 8010
Total incoming mockups in February 2024: 7925

In [106]:
#How many of the Incoming requests converted, i.e made it to mfg_products

# Convert the timestamp in manufacturing products DataFrame and filter
cleaned_design_mfg_products_df['Created_at'] = pd.to_datetime(cleaned_design_mfg_products_df['Created_at'])
mfg_feb_mar = cleaned_design_mfg_products_df[
    (cleaned_design_mfg_products_df['Created_at'] >= '2023-02-01') &
    (cleaned_design_mfg_products_df['Created_at'] <= '2023-03-31')
]

# Find intersecting Mockup_IDs that were converted to manufacturing products
converted_mockups = february_mockups[february_mockups['Mockup_ID'].isin(mfg_feb_mar['Mockup_ID'])]
total_converted_mockups = converted_mockups['Mockup_ID'].nunique()
print("Total converted mockups:", total_converted_mockups)

# Filter the manufacturing products DataFrame for February and March 2024
mfg_feb_mar_2024 = cleaned_design_mfg_products_df[
    (cleaned_design_mfg_products_df['Created_at'] >= '2024-02-01') &
    (cleaned_design_mfg_products_df['Created_at'] <= '2024-03-31')
]

# Find intersecting Mockup_IDs that were converted to manufacturing products
converted_mockups_2024 = february_2024_mockups[february_2024_mockups['Mockup_ID'].isin(mfg_feb_mar_2024['Mockup_ID'])]
total_converted_mockups_2024 = converted_mockups_2024['Mockup_ID'].nunique()
print("Total converted mockups in 2024:", total_converted_mockups_2024)

Total converted mockups: 496
Total converted mockups in 2024: 636

In [107]:
#What was the total, average, stdev #What was the total, mean, and std dev 
# of the quantities for those mockups that turned into mfg_products?
# Filter manufacturing DataFrame to only include converted mockups
converted_quantities = mfg_feb_mar[mfg_feb_mar['Mockup_ID'].isin(converted_mockups['Mockup_ID'])]

# Calculate total, mean, and std deviation of quantities
total_quantity = converted_quantities['Quantity'].sum()
mean_quantity = converted_quantities['Quantity'].mean()
std_dev_quantity = converted_quantities['Quantity'].std()

print(f"Total Quantity in 2023: {total_quantity}")
print(f"Mean Quantity in 2023: {mean_quantity}")
print(f"Standard Deviation of Quantity in 2023: {std_dev_quantity}")

# Filter manufacturing DataFrame to only include converted mockups for 2024
converted_quantities_2024 = mfg_feb_mar_2024[mfg_feb_mar_2024['Mockup_ID'].isin(converted_mockups_2024['Mockup_ID'])]

# Calculate total, mean, and std deviation of quantities
total_quantity_2024 = converted_quantities_2024['Quantity'].sum()
mean_quantity_2024 = converted_quantities_2024['Quantity'].mean()
std_dev_quantity_2024 = converted_quantities_2024['Quantity'].std()

print(f"Total Quantity in 2024: {total_quantity_2024}")
print(f"Mean Quantity in 2024: {mean_quantity_2024}")
print(f"Standard Deviation of Quantity in 2024: {std_dev_quantity_2024}")

Total Quantity in 2023: 142573
Mean Quantity in 2023: 224.17138364779873
Standard Deviation of Quantity in 2023: 393.74187619502516
Total Quantity in 2024: 139807
Mean Quantity in 2024: 172.81458590852904
Standard Deviation of Quantity in 2024: 251.83644844856352