In [4]:
# Import dependencies
import pandas as pd
import numpy as np

In [ ]:
# declare modified dfs 
modified_deal_df = pd.read_csv('../Modified_Data_Resources/modified_deal_info.csv')
modified_mockups_df = pd.read_csv('../Modified_Data_Resources/modified_mockups_info.csv')
modified_revisions_df = pd.read_csv('../Modified_Data_Resources/revisions_df_copy.csv')
modified_cart_items_df = pd.read_csv('../Modified_Data_Resources/modified_cart_items_info.csv')
modified_mfg_products_df = pd.read_csv('../Modified_Data_Resources/mfg_products_df_copy.csv')
modified_deals_mockups_df = pd.read_csv('../Modified_Data_Resources/deals_mockups_df_copy.csv')

In [ ]:
modified_deal_df.info()
cleaned_deal_df = pd.DataFrame(modified_deal_df)

# Drop columns where all elements are NaN
cleaned_deal_df = modified_deal_df.dropna(axis=1, how='all')

# Print the DataFrame before and after dropping columns
print(cleaned_deal_df)

In [ ]:
#filter down columns to create schema specific for design team queries

In [ ]:
modified_deal_df.info()

In [ ]:
# Check if each ID in 'modified_deal_df' exists in 'Deal ID' of 'modified_deals_mockups_df'
id_exists = modified_deal_df['ID'].isin(modified_deals_mockups_df['Deal ID'])

# Add this as a new column to 'modified_deal_df' if you want to keep track
modified_deal_df['ID Exists in Mockups'] = id_exists

# Display the result
modified_deal_df[['ID', 'ID Exists in Mockups']].info()

In [ ]:
#filter for just how many rows have matches between ID and Deal ID
matching_rows = modified_deal_df[modified_deal_df['ID'].isin(modified_deals_mockups_df['Deal ID'])]
matching_rows.info()

In [ ]:
# If ID is in deals_mockups the mockup id is in mockups ID

In [29]:
# Clean up modified deal_df
# Only keep key columns for design schema

import pandas as pd

# Sample data creation for demonstration; replace this with your actual DataFrame loading method
# data = {...}
# modified_deal_df = pd.DataFrame(data)

# Dictionary for renaming columns
rename_columns = {
    'ID': 'Deal_Table_Record_ID',
    'Created at': 'Deal_Created_at',
    'Updated at': 'Deal_Updated_at',
    'Originial due at': 'Deal_Original_Due_at',
    'Due at': 'Deal_Due_at',
    'Assigned at': 'Deal_assigned_at',
    'Mockups ready at': 'Mockups_ready_at',  # Assuming you want to keep the name as is, add the correct new name if needed
    'Mockup due date': 'Mockup_due_date',  # Assuming you want to keep the name as is, add the correct new name if needed
    'Hs quantity': 'Hs_quantity',  # Assuming you want to keep the name as is, add the correct new name if needed
    'Hs client type': 'Hs_client_type',  # Assuming you want to keep the name as is, add the correct new name if needed
    'Po number': 'Po_number',  # Assuming you want to keep the name as is, add the correct new name if needed
    'Portal created': 'Portal_created',  # Assuming you want to keep the name as is, add the correct new name if needed
    'Hs design difficulty': 'Hs_design_difficulty',  # Assuming you want to keep the name as is, add the correct new name if needed
    'Automation tool': 'Automation_tool',  # Assuming you want to keep the name as is, add the correct new name if needed
    'Viewed designs': 'Viewed_designs',  # Assuming you want to keep the name as is, add the correct new name if needed
    'Hs dealtype': 'Hs_dealtype',  # Assuming you want to keep the name as is, add the correct new name if needed
    'Created on': 'Deal_Created_on'  # Assuming you want to rename to this
}

# Filter and rename columns in the DataFrame
cleaned_design_deal_df = modified_deal_df[list(rename_columns.keys())].rename(columns=rename_columns)

# Display the new DataFrame
cleaned_design_deal_df

,Deal_Table_Record_ID,Deal_Created_at,Deal_Updated_at,Deal_Original_Due_at,Deal_Due_at,Deal_assigned_at,Mockups_ready_at,Mockup_due_date,Hs_quantity,Hs_client_type,Po_number,Portal_created,Hs_design_difficulty,Automation_tool,Viewed_designs,Hs_dealtype,Deal_Created_on
0,105010,2023-01-01T19:01:33.103Z,2024-02-09T00:35:28.466Z,2023-01-04T19:01:33.000Z,2023-01-04T19:01:33.000Z,2023-01-03T15:28:27.124Z,2023-01-03T17:14:33.056Z,2023-01-04T06:00:00.000Z,NaN,Direct,NaN,True,Low,1.0,NaN,Newbusiness,2023-01-01
1,105014,2023-01-01T23:52:14.779Z,2023-03-02T22:51:26.182Z,2023-01-04T23:52:16.000Z,2023-01-04T23:52:16.000Z,2023-01-03T15:28:57.563Z,2023-01-03T15:34:23.973Z,2023-01-04T06:00:00.000Z,NaN,Direct,NaN,True,High Res Preview,2.0,NaN,Newbusiness,2023-01-01
2,105006,2023-01-01T04:58:07.689Z,2023-01-11T15:50:19.497Z,NaN,NaN,NaN,NaN,NaN,NaN,Direct,NaN,True,NaN,1.0,NaN,Newbusiness,2023-01-01
3,105011,2023-01-01T20:05:07.001Z,2023-03-28T15:29:19.886Z,2023-01-04T20:05:09.000Z,2023-01-04T20:05:09.000Z,2023-01-03T15:30:15.651Z,2023-01-03T22:16:32.764Z,2023-01-04T06:00:00.000Z,NaN,Direct,NaN,True,Low,2.0,NaN,Newbusiness,2023-01-01
4,105007,2023-01-01T14:26:53.422Z,2023-01-16T19:29:55.241Z,2023-01-04T14:26:55.000Z,2023-01-04T14:26:55.000Z,2023-01-03T15:29:39.647Z,NaN,2023-01-04T06:00:00.000Z,NaN,Direct,NaN,True,High Res Preview,2.0,NaN,Newbusiness,2023-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32008,141542,2024-04-09T17:11:34.705Z,2024-04-09T20:53:51.741Z,2024-04-12T17:12:18.000Z,2024-04-12T17:12:18.000Z,NaN,NaN,2024-04-10T17:12:18.000Z,NaN,Distributor,50819.0,NaN,High Res Preview,NaN,NaN,Existingbusiness,2024-04-09
32009,141550,2024-04-09T17:40:18.487Z,2024-04-09T21:17:37.165Z,2024-04-12T19:39:38.000Z,2024-04-12T19:39:38.000Z,NaN,NaN,2024-04-10T17:43:51.000Z,NaN,Distributor,50827.0,NaN,Low,NaN,NaN,Existingbusiness,2024-04-09
32010,141556,2024-04-09T18:03:42.179Z,2024-04-09T21:23:27.344Z,2024-04-12T18:06:40.000Z,1969-12-30T23:15:32.000Z,2024-04-09T19:40:10.101Z,2024-04-09T21:23:27.343Z,2024-04-09T18:06:43.000Z,NaN,Distributor,50833.0,NaN,Low,NaN,NaN,Existingbusiness,2024-04-09
32011,141541,2024-04-09T17:08:51.902Z,2024-04-09T20:53:37.732Z,2024-04-12T17:08:52.000Z,2024-04-12T17:08:52.000Z,NaN,NaN,2024-04-10T17:08:52.000Z,NaN,Distributor,50818.0,True,Low,1.0,NaN,Existingbusiness,2024-04-09
32012,141551,2024-04-09T17:41:10.568Z,2024-04-09T20:56:09.058Z,2024-04-12T17:45:19.000Z,2024-04-12T17:45:19.000Z,NaN,NaN,2024-04-10T17:45:19.000Z,NaN,Distributor,50828.0,NaN,High Res Preview,NaN,NaN,Existingbusiness,2024-04-09

In [ ]:
# clean up modified mockup df, only keep key columns for design schema


# Dictionary for renaming columns
rename_columns = {
    'ID': 'Mockup_ID',
    'Created at': 'mockup_created_at',
    'Updated at': 'Mockup_updated_at',
    'Version number': 'Version_number',  # Assuming you want to keep the name as is
    'Design number': 'Design_number',  # Assuming you want to keep the name as is
    'Chassis': 'Chassis',  # Assuming you want to keep the name as is
    'Previously ordered': 'Previously_ordered',  # Assuming you want to keep the name as is
    'Design source': 'Design_source',  # Assuming you want to keep the name as is
    'Designer ID': 'Designer_ID',  # Assuming you want to keep the name as is
    'Parent mockup ID': 'Parent_mockup_ID'  # Assuming you want to keep the name as is
}

# Filter and rename columns in the DataFrame
cleaned_design_mockup_df = modified_mockups_df[list(rename_columns.keys())].rename(columns=rename_columns)

# Display the new DataFrame
print(cleaned_design_mockup_df)

In [39]:
# clean up modified mockup df, only keep key columns for design schema


# Dictionary for renaming columns
rename_columns = {
    'ID': 'Deals_mockups_ID',
    'Created at': 'Deals_Mockups_created_at',
    'Updated at': 'Deals_Mockups_updated_at'
}

# Columns to keep (including those to be renamed and those not renamed but still retained)
columns_to_keep = ['ID', 'Deal ID', 'Mockup ID', 'Created at', 'Updated at']

# Filter and rename columns in the DataFrame
cleaned_design_deals_mockups_df = modified_deals_mockups_df[columns_to_keep].rename(columns=rename_columns)

# Display the new DataFrame
print(cleaned_design_deals_mockups_df)

       Deals_mockups_ID  Deal ID  Mockup ID  Deals_Mockups_created_at  \
0                136844   105007     134249  2023-01-01T14:26:55.273Z
1                136847   105011     134252  2023-01-01T20:05:08.783Z
2                136848   105014     134253  2023-01-01T23:52:16.712Z
3                136843   105006     134248  2023-01-01T05:02:06.781Z
4                136851   105036     134256  2023-01-02T22:04:52.688Z
...                 ...      ...        ...                       ...
97581            247960   141537     235655  2024-04-10T18:10:10.279Z
97582            247976   141605     235670  2024-04-10T18:42:26.894Z
97583            247975   141646     235669  2024-04-10T18:40:47.727Z
97584            247967   141623     235244  2024-04-10T18:15:39.304Z
97585            247962   141534     235657  2024-04-10T18:10:19.471Z

       Deals_Mockups_updated_at
0      2023-01-01T14:26:55.273Z
1      2023-01-01T20:05:08.783Z
2      2023-01-01T23:52:16.712Z
3      2023-01-01T05:02:06.781Z
4      2023-01-02T22:04:52.688Z
...                         ...
97581  2024-04-10T18:10:10.279Z
97582  2024-04-10T18:42:26.894Z
97583  2024-04-10T18:40:47.727Z
97584  2024-04-10T18:15:39.304Z
97585  2024-04-10T18:10:19.471Z

[97586 rows x 5 columns]

In [32]:
# clean up modified cart items df, only keep key columns for design schema


# Dictionary for renaming columns
rename_columns = {
    'ID': 'cart_items_id',
    'Created at': 'Created_at',  # Assuming you want to keep the name almost similar but properly formatted
    'Quantity': 'Quantity',
    'Deal ID': 'Deal_ID',
    'Mockup ID': 'Mockup_ID',
    'Mockup version': 'Mockup_version',
    'Sock unit price': 'Sock_unit_price',
    'Pkg unit price': 'Pkg_unit_price',
    'Product ID': 'Product_ID',
    'Unit price': 'Unit_price',
    'Cart total': 'Cart_total',
    'Created on': 'Created_on'
}

# Columns to keep (specify columns here that you wish to keep in the new DataFrame)
columns_to_keep = list(rename_columns.keys())

# Filter and rename columns in the DataFrame
cleaned_design_cart_items_df = modified_cart_items_df[columns_to_keep].rename(columns=rename_columns)

# Display the new DataFrame
cleaned_design_cart_items_df.head()

,cart_items_id,Created_at,Quantity,Deal_ID,Mockup_ID,Mockup_version,Sock_unit_price,Pkg_unit_price,Product_ID,Unit_price,Cart_total,Created_on
0,68849,2023-01-01T21:40:49.192Z,NaN,NaN,NaN,NaN,NaN,$1.00,NaN,NaN,180.0,2023-01-01
1,68848,2023-01-01T21:40:49.178Z,180.0,NaN,133806.0,3.0,$11.12,NaN,NaN,NaN,180.0,2023-01-01
2,68878,2023-01-03T18:08:48.367Z,1600.0,NaN,130725.0,1.0,$5.68,NaN,NaN,NaN,2000.0,2023-01-03
3,68879,2023-01-03T18:37:22.407Z,NaN,NaN,NaN,NaN,NaN,$1.00,NaN,NaN,200.0,2023-01-03
4,68927,2023-01-03T22:10:37.877Z,NaN,NaN,NaN,NaN,NaN,$1.00,NaN,NaN,120.0,2023-01-03

In [35]:
# clean up modified revision df, keep key columns for design schema and rename


# Dictionary for renaming columns
rename_columns = {
    'ID': 'revisions_ID',
    'Mockup ID': 'Mockup_ID',  # Assuming you want to keep the name as is
    'Version number': 'Version_number',  # Assuming you want to keep the name as is
    'Completed at': 'Completed_at',  # Assuming you want to keep the name almost similar but properly formatted
    'Created at': 'Created_at',  # Assuming you want to keep the name almost similar but properly formatted
    'Updated at': 'Updated_at',  # Assuming you want to keep the name almost similar but properly formatted
    'Packaging ID': 'Packaging_ID',  # Assuming you want to keep the name as is
    'Product ID': 'Product_ID',  # Assuming you want to keep the name as is
    'Sock pair ID': 'Sock_pair_ID',  # Assuming you want to keep the name as is
    'Base version': 'Base_version',  # Assuming you want to keep the name as is
    'Read at': 'Read_at'  # Assuming you want to keep the name almost similar but properly formatted
}

# Columns to keep (specify columns here that you wish to keep in the new DataFrame)
columns_to_keep = list(rename_columns.keys())

# Filter and rename columns in the DataFrame
cleaned_design_revisions_df = modified_revisions_df[columns_to_keep].rename(columns=rename_columns)

# Display the new DataFrame
cleaned_design_revisions_df.head()

,revisions_ID,Mockup_ID,Version_number,Completed_at,Created_at,Updated_at,Packaging_ID,Product_ID,Sock_pair_ID,Base_version,Read_at
0,21736,133806.0,3.0,2023-01-03T15:43:58.337Z,2023-01-01T21:34:49.498Z,2023-01-03T15:43:58.338Z,NaN,NaN,NaN,3.0,NaN
1,21810,134477.0,1.0,2023-01-04T18:13:20.532Z,2023-01-03T23:59:17.506Z,2023-01-04T18:13:20.532Z,NaN,NaN,NaN,1.0,NaN
2,21750,133944.0,2.0,2023-01-03T17:17:10.792Z,2023-01-03T17:08:33.855Z,2023-01-03T17:17:10.793Z,NaN,NaN,NaN,2.0,NaN
3,21782,133993.0,3.0,2023-01-03T21:02:49.165Z,2023-01-03T20:51:33.167Z,2023-01-03T21:02:49.166Z,NaN,NaN,NaN,3.0,NaN
4,21806,134492.0,1.0,2023-01-04T17:58:43.091Z,2023-01-03T23:48:34.490Z,2023-01-04T17:58:43.091Z,NaN,NaN,NaN,1.0,NaN

In [37]:
# clean up modified mfg products df, keep key columns for design schema and rename


# Dictionary for renaming columns
rename_columns = {
    'ID': 'mfg_products_ID',
    'Mockup ID': 'Mockup_ID',  # Assuming you want to keep the name as is
    'Created at': 'Created_at',  # Assuming you want to keep the name almost similar but properly formatted
    'Updated at': 'Updated_at',  # Assuming you want to keep the name almost similar but properly formatted
    'Packaging ID': 'Packaging_ID',  # Assuming you want to keep the name as is
    'Product ID': 'Product_ID',  # Assuming you want to keep the name as is
    'Sock pair ID': 'Sock_pair_ID',  # Assuming you want to keep the name as is
    'Created on': 'Created_on',  # Assuming you want to keep the name almost similar but properly formatted
    'Mockup version': 'Mockup_version',  # Assuming you want to keep the name as is
    'Quantity': 'Quantity',  # Assuming you want to keep the name as is
    'Product info ID': 'Product_info_ID'  # Assuming you want to keep the name as is
}

# Columns to keep (specify columns here that you wish to keep in the new DataFrame)
columns_to_keep = list(rename_columns.keys())

# Filter and rename columns in the DataFrame
cleaned_design_mfg_products_df = modified_mfg_products_df[columns_to_keep].rename(columns=rename_columns)

# Display the new DataFrame
cleaned_design_mfg_products_df.head()

,mfg_products_ID,Mockup_ID,Created_at,Updated_at,Packaging_ID,Product_ID,Sock_pair_ID,Created_on,Mockup_version,Quantity,Product_info_ID
0,36734,NaN,2023-01-02T21:05:25.023Z,2023-01-02T21:05:25.418Z,65927.0,NaN,NaN,2023-01-02,NaN,500.0,35.0
1,36733,112571.0,2023-01-02T21:05:25.018Z,2023-01-02T21:05:25.347Z,NaN,NaN,NaN,2023-01-02,4.0,500.0,2.0
2,36772,NaN,2023-01-03T18:12:05.569Z,2023-01-03T18:18:42.153Z,70799.0,NaN,NaN,2023-01-03,NaN,1600.0,35.0
3,36781,118940.0,2023-01-03T20:07:39.098Z,2023-01-03T20:07:39.611Z,NaN,NaN,NaN,2023-01-03,1.0,60.0,114.0
4,36782,NaN,2023-01-03T20:07:39.103Z,2023-01-03T20:07:39.679Z,68963.0,NaN,NaN,2023-01-03,NaN,60.0,35.0

In [ ]:
modified_cart_items_df.to_csv('../Modified_Data_Resources/modified_cart_items_info.csv', index=False)

In [41]:
import os

# Directory where the CSV files will be saved
directory = 'Cleaned_Design_Data_Resources'

# Create the directory if it doesn't exist
if not os.path.exists(directory):
    os.makedirs(directory)

# List of DataFrames and their corresponding file names
dataframes = {
    'cleaned_design_deal_df': cleaned_design_deal_df,
    'cleaned_design_mockup_df': cleaned_design_mockup_df,
    'cleaned_design_deals_mockups_df': cleaned_design_deals_mockups_df,
    'cleaned_design_cart_items_df': cleaned_design_cart_items_df,
    'cleaned_design_revisions_df': cleaned_design_revisions_df,
    'cleaned_design_mfg_products_df': cleaned_design_mfg_products_df
}

# Save each DataFrame as a CSV file
for file_name, df in dataframes.items():
    csv_path = os.path.join(directory, f"{file_name}.csv")
    df.to_csv(csv_path, index=False)  # Set index=False if you don't want to save row indices

print("All cleaned DataFrames have been saved as CSV files in the directory:", directory)

All cleaned DataFrames have been saved as CSV files in the directory: Cleaned_Design_Data_Resources